import i1 from "../../assets/images/Donation/1.png";
import i2 from "../../assets/images/Donation/2.png";
import i3 from "../../assets/images/Donation/3.png";
import i4 from "../../assets/images/Donation/4.png";
import i5 from "../../assets/images/Donation/5.png";
import i6 from "../../assets/images/Donation/6.png";

export const donationData = [
  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },  { image: i1, type: "Food", percentage: "55", goal: "20", fund: "14", progress: "70" },
  { image: i2, type: "Education", percentage: "55", goal: "30", fund: "24", progress: "30" },
  { image: i3, type: "Donate", percentage: "55", goal: "40", fund: "34", progress: "80" },
  { image: i4, type: "Medicine", percentage: "55", goal: "50", fund: "44", progress: "50" },
  { image: i5, type: "Fund", percentage: "55", goal: "60", fund: "54", progress: "60" },
  { image: i6, type: "Home", percentage: "55", goal: "70", fund: "64", progress: "20" },
  // add more cards here later 👈
];